# Generated by Django 6.0.2 on 2026-02-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_app', '0002_bbqitem_eventitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bbqitem',
            old_name='bbq_item',
            new_name='name',
        ),
        migrations.AddField(
            model_name='bbqitem',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
