# Generated by Django 6.0.2 on 2026-02-22 02:09

from django.db import migrations, models
from datetime import datetime

def forwards(apps, schema_editor):
    Event = apps.get_model("bbq_app", "Event")
    for e in Event.objects.all():
        if e.held_at is None:
            e.held_at = datetime.combine(e.date, e.time)
            e.save(update_fields=["held_at"])
            
def backwards(apps, schema_editor):
    Event = apps.get_model("bbq_app", "Event")
    for e in Event.objects.all():
        if e.held_at:
            e.date = e.held_at.date()
            e.time = e.held_at.time()
            e.save(update_fields=["date", "time"])

class Migration(migrations.Migration):

    dependencies = [
        ('bbq_app', '0003_rename_bbq_item_bbqitem_name_bbqitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='held_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='開催日時'),
        ),
        migrations.RunPython(forwards, backwards),
    ]
