# Generated by Django 6.0.2 on 2026-02-22 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_app', '0004_event_held_at'),
    ]

    operations = [
    ]
