# Generated by Django 6.0.2 on 2026-02-22 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_app', '0005_auto_20260222_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
    ]
