# Generated by Django 6.0.2 on 2026-02-28 14:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_app', '0006_remove_event_date_remove_event_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventitem',
            name='status',
        ),
        migrations.AddField(
            model_name='bbqitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bbqitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='eventitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventitem',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bbqitem',
            name='category',
            field=models.IntegerField(choices=[(1, '火起こし・調理グッズ'), (2, '会場設営'), (3, '食材・持ち物'), (4, '便利グッズ'), (5, 'その他')]),
        ),
        migrations.AlterField(
            model_name='bbqitem',
            name='name',
            field=models.CharField(max_length=50, verbose_name='持ち物名'),
        ),
        migrations.AlterField(
            model_name='bbqitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bbq_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=50, verbose_name='開催場所'),
        ),
        migrations.AlterField(
            model_name='eventitem',
            name='bbq_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_items', to='bbq_app.bbqitem'),
        ),
        migrations.AlterField(
            model_name='eventitem',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_items', to='bbq_app.event'),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='表示名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='bbq_app.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=300, unique=True)),
                ('guest_name', models.CharField(max_length=30)),
                ('status', models.IntegerField(choices=[(0, 'pending'), (1, 'active'), (2, 'expired'), (3, 'revoked')], default=0)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='bbq_app.participant')),
            ],
        ),
        migrations.AddField(
            model_name='eventitem',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_items', to='bbq_app.participant'),
        ),
        migrations.AddConstraint(
            model_name='eventitem',
            constraint=models.UniqueConstraint(fields=('event', 'bbq_item'), name='unique_event_bbq_item'),
        ),
    ]
