# Generated by Django 6.0.2 on 2026-03-06 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_app', '0007_remove_eventitem_status_bbqitem_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbqitem',
            name='category',
            field=models.IntegerField(choices=[(1, '火起こし・調理グッズ'), (2, '会場設営'), (3, '食材・飲み物'), (4, '便利グッズ'), (5, 'その他')]),
        ),
        migrations.AlterField(
            model_name='bbqitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bbq_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
